### ISSUE TITLE
Compilation fails on Ubuntu Bionic for Pg12

### ISSUE THREAD

**Issue by depesz** [yandex/odyssey#303]
I tried to compile odyssey on Ubuntu Bionic with Pg 12. Unfortunately it fails with lots of errors re:

```
In file included from /home/depesz/src/odyssey/sources/odyssey.h:51:0,                     
                 from /home/depesz/src/odyssey/sources/scram.c:10:
/home/depesz/src/odyssey/sources/scram.c: In function ‘od_scram_parse_verifier’:            
/home/depesz/src/odyssey/sources/scram.h:8:2: error: too many arguments to function ‘pg_b64_decode’
  pg_b64_decode(src, src_len, dst, dst_len);                        
  ^                                                                    
/home/depesz/src/odyssey/sources/scram.c:65:3: note: in expansion of macro ‘od_b64_decode’
   od_b64_decode(salt_raw, salt_raw_len, salt, salt_dst_len);     
   ^~~~~~~~~~~~~                                                            
```

Unfortunately we can't use Pg 13, yet, on production, Is there any way to compile is for Pg12?

**Comment by x4m** [comment]
Hi! Glad to see you here, your site taught me what PG queries actually do :)

Odyssey builds against protocol libs of PG. But Odyssey binary build for PG13 works fine with PG10-13. Yandex.Cloud currently installs the same binary for all PG versions.

We really want to provide apt\yum installation, but did not succeseeded yet. That's why we are not 1.2 yet.

**Comment by depesz** [comment]
OK. Thanks. Will try to get it work.
