### ISSUE TITLE
¿What is the official Odysee Repo?

### ISSUE THREAD

**Issue by juanpc2018** [yandex/odyssey#426]
this:
https://github.com/OdyseeTeam/odysee-frontend/

or this:
https://github.com/yandex/odyssey/

????
Anyway i have a BUG....
#1.
when a Video link is posted on Telegram, 
does Not have a Preview Window, like YouTube.

#2. Keys 1,2,3,4,5,6,7,8,9,0 in YouTube jump Timeline 10%, 20%, 30%, ... 0%

Odysee only has J & L
Spacebar
F

**Comment by x4m** [comment]
Hi! [Odyssey](https://en.wikipedia.org/wiki/Odyssey) is a story of Odysseus sailing here and there, doing stuff, drinking wine, killing suitors etc. It's a great peace of literature, that's why so many programmers named their projects 'Odyssey'. So we did too.
This is an official repo of a scalable connection pooler for PostgreSQL. This program relay bytes between sockets in a way that PostgreSQL (a database program) have limited number of concurrent transactions. And this Odyssey does this on many CPUs at a time.
That's it.  It has nothing to do with Youtube.
Feel free to reopen if you have any questions.
