### ISSUE TITLE
Google Summer of Code 2019 with PostgreSQL

### ISSUE THREAD

**Issue by x4m** [yandex/odyssey#47]
Hi!

How about participating in GSoC 2019?
If necessary I'm OK with co-mentoring, but we need some decent idea to be put here
https://wiki.postgresql.org/wiki/GSoC_2019
Currently, I'm not enough in context for our roadmap to generate project idea, but I can help form and apply one.

The deadline for Mentoring organizations to apply is: February 6.
The list of accepted organization will be published around February 26.

So, I think if we want it we should put a project idea in January.

**Comment by x4m** [comment]
I've created a stub here
https://wiki.postgresql.org/wiki/GSoC_2019#Read.2Fwrite_transaction-level_routing_in_Odyssey_.282019.29
We should add their info to help students to compose their project proposals.
@pmwkaa if you can participate as a mentor in the project, please add your name in mentors list (or ping me to add it, I already possess write access to wiki :) ).

**Comment by shaaza** [comment]
@x4m I just came across this via GSoC, and found it interesting. I can relate to #1 and #2 well.

The features mentioned in the GSoc Ideas List wiki are:

1. Redirecting read query on standby only if standby is lagging no more than X seconds
2. Redirecting read query on standby unless there was recent write (writer should see his writes)
3. Redirecting some read queries on syn or async standby

I'm curious how these would be implemented:
1. *Read if rep. lag <X s*: Does Odyssey already track replication lag of standbys, or will it need to periodically query standbys to compute replication lag using something like `pg_last_xact_replay_timestamp()`?

2. *Read-after-writes*: Doesn't this require one to track some 'recent writes' state (i.e. request contexts/ids of recent writes against which subsequent reads can be matched, where 'recent' is defined by a time window)? Currently I see that database+user info is used to match requests to rules. Since recency-of-writes based routing seems to imply some dynamic state, did you have a strategy in mind to implement this that is in line with current architecture of the odyssey library?

3. Could you expand on this a bit? Is it just generally load balancing across read-slaves? Replication lag would be a factor here too, right?

Apologies if these questions are naive - feel free to point me to other resources if I can find answers elsewhere (code, mailing lists, wiki etc.)

**Comment by x4m** [comment]
@shaaza Hi! Sorry for the late reply right before GSoC deadline.
>Does Odyssey already track replication lag of standbys?
No
>Doesn't this require one to track some 'recent writes' state? 
Yes, and this is required by routing-to-standby feature too.
>did you have a strategy in mind to implement this that is in line with current architecture of the odyssey library?
No. This is kind of reaserch project.
>Is it just generally load balancing across read-slaves?
Yes
>Replication lag would be a factor here too, right?
If possible
>Could you expand on this a bit?
Reading from standby without remote_write is inconsistent. This is GSoC project idea for a student to reaserch into possible cheap ways of makeing Postgres scaling-out for reads consistent.

**Comment by x4m** [comment]
Well, maybe next year. Closing for now.

**Comment by AnkilP** [comment]
I'm interested in this (for 2020) - do the above answers still apply?
