### ISSUE TITLE
SCRAM auth in database and user route

### ISSUE THREAD

**Issue by harthurd** [yandex/odyssey#484]
Hi!
Looks like the above doesn't work:
```
database "my_database" {
         user "my_user" {
                authentication "scram-sha-256"
                password "SCRAM-SHA-256$4096:pPS1NUydBHcrytDIHW...zfKlE2A="
```
Only plaintext works in the "password" field.
There is such an error: `psql: ошибка: ERROR:  odyssey: c3bde3d7718dd: password authentication failed`

**Comment by iihero** [comment]
md5 also can work.  But scram-sha-256 seems failed to work.
Not sure why the document says it can support.

**Comment by reshke** [comment]
> Hi! Looks like the above doesn't work:
> 
> ```
> database "my_database" {
>          user "my_user" {
>                 authentication "scram-sha-256"
>                 password "SCRAM-SHA-256$4096:pPS1NUydBHcrytDIHW...zfKlE2A="
> ```
> 
> Only plaintext works in the "password" field. There is such an error: `psql: ошибка: ERROR: odyssey: c3bde3d7718dd: password authentication failed`

You need to fill up `storage_password` setting with plain-text version of your password for backend auth(odyssey<->pg) to work. This password will be used by odyssey for acquiring connection to database. Md5 password also works exactly this way, except you can fill up `password ` setting with md5(password +user) value and everything will work just fine (this is because in the case of md5-auth only this hash version of password needed, not the password itself).

Pgbouncer also require plain text password in scram-sha-256.

There is ways to avoid plain text passwords on config, but they are too complicated, so I will not describe them
